name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify_with_base_tests:
    runs-on: ubuntu-latest
    environment: CI_TEST
    env:
      GPT3_5_APIKEY: ${{ secrets.GPT3_5_APIKEY }}
      GPT3_5_URL: ${{ secrets.GPT3_5_URL }}
      GPT4_APIKEY: ${{ secrets.GPT4_APIKEY }}
      GPT4_URL: ${{ secrets.GPT4_URL }}
      ROARR_LOG: true

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Run tests
      run: yarn test
