name: 'Test Coverage'
on: 
  workflow_dispatch:

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    environment: CI_TEST
    env:
      GPT3_5_APIKEY: ${{ secrets.GPT3_5_APIKEY }}
      GPT3_5_URL: ${{ secrets.GPT3_5_URL }}
      GPT4_APIKEY: ${{ secrets.GPT4_APIKEY }}
      GPT4_URL: ${{ secrets.GPT4_URL }}
      GPT3_5_I_APIKEY: ${{ secrets.GPT3_5_I_APIKEY }}
      GPT3_5_I_URL: ${{ secrets.GPT3_5_I_URL }}
      ROARR_LOG: true
      NODE_ENV: development
    
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: 'Install Deps'
      run: yarn install
    - name: 'Test'
      run: yarn coverage
    - name: 'Report Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v2
